version: '3'

services:
  db:
    image: postgis/postgis
    env_file:
      - ./.envs/.postgres
    ports:
    - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
  app:
    build: .
    command: gunicorn mozio_project.wsgi:application -w 2 -b :8000 --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-
    env_file:
      - ./.envs/.postgres
      - ./.envs/.django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    postgis_data: